#!/bin/sh -e

#DISABLE_IPV6=1

if [ "$1" = '-f' ]; then
  echo force run
fi

if [ -z "$2" ]; then
  [ "$INTERFACE" = cf ] || exit 0
  [ "$ACTION" = ifup ] || exit 0
else
  DEVICE="$2"
  echo run on "$2"
fi

CONFDIR=/etc/chnroutes

ip r f proto 114
ip -6 r f proto 114
for f in $CONFDIR/*; do
  if [ "$f" = "$CONFDIR/chnroute" ]; then
    continue
  fi
  grep -qF skip "$f" && continue
  while read p; do
    echo "$p" | grep -qF '#' && continue
    [ "$DISABLE_IPV6" = 1 ] && echo "$p" | grep -qF : && continue
    if ! ip r a "$p" dev "$DEVICE" proto 114; then
      [ "$1" = '-f' ] || exit 1
      echo "$f: $p"
    fi
  done < "$f"
done
